/*
 * Copyright 2018 Murat Artim (muratartim@gmail.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package equinox.utility;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;

import equinox.Equinox;

/**
 * Utility class for PDF report footer.
 *
 * @author Murat Artim
 * @date Apr 4, 2016
 * @time 1:36:52 PM
 */
public class ReportFooter extends PdfPageEventHelper {

	/** Footer font. */
	private final Font font_ = new Font(Font.FontFamily.UNDEFINED, 10, Font.ITALIC, BaseColor.WHITE);

	/** Creation date and title. */
	private final String date_, title_;

	/**
	 * Creates PDF report footer.
	 *
	 * @param title
	 *            Document title.
	 */
	public ReportFooter(String title) {
		date_ = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
		title_ = title;
	}

	@Override
	public void onEndPage(PdfWriter writer, Document document) {

		// do not add on first page
		if (document.getPageNumber() == 1)
			return;

		// get canvas
		PdfContentByte canvas = writer.getDirectContent();

		// create top rectangle
		Rectangle topRectangle = new Rectangle(0, document.top() + 10, document.right() + document.rightMargin(), document.top() + document.topMargin());
		topRectangle.setBackgroundColor(new BaseColor(70, 130, 180));
		canvas.rectangle(topRectangle);

		// create bottom rectangle
		Rectangle bottomRectangle = new Rectangle(0, 0, document.right() + document.rightMargin(), document.bottom() - 20);
		bottomRectangle.setBackgroundColor(new BaseColor(70, 130, 180));
		canvas.rectangle(bottomRectangle);

		// write top-right footer (creation date)
		Phrase topRight = new Phrase("Date: " + date_, font_);
		ColumnText.showTextAligned(canvas, Element.ALIGN_RIGHT, topRight, document.right(), document.top() + 20, 0);

		// write top-left footer (title)
		Phrase topLeft = new Phrase(title_, font_);
		ColumnText.showTextAligned(canvas, Element.ALIGN_LEFT, topLeft, document.left(), document.top() + 20, 0);

		// write bottom-right footer (page number)
		Phrase bottomRight = new Phrase("Page " + document.getPageNumber(), font_);
		ColumnText.showTextAligned(canvas, Element.ALIGN_RIGHT, bottomRight, document.right(), document.bottom() - 40, 0);

		// write bottom-left footer (Equinox version)
		Phrase bottomLeft = new Phrase("Generated by Equinox version " + Equinox.VERSION.toString(), font_);
		ColumnText.showTextAligned(canvas, Element.ALIGN_LEFT, bottomLeft, document.left(), document.bottom() - 40, 0);
	}
}
